package com.example.secondphone.service;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.example.secondphone.dto.*;
import com.example.secondphone.entity.*;
import com.example.secondphone.exception.*;
import com.example.secondphone.repository.*;

@Service
public class CheckoutService {
    private static final Set<String> PAYMENT_METHODS=Set.of("DEMO_CARD","CASH_ON_DELIVERY");
    private final OrderRepository orders;private final OrderItemRepository orderItems;private final ProductRepository products;private final CartService carts;
    public CheckoutService(OrderRepository orders,OrderItemRepository orderItems,ProductRepository products,CartService carts){this.orders=orders;this.orderItems=orderItems;this.products=products;this.carts=carts;}
    @Transactional public OrderDetailResponse checkout(String account,CheckoutRequest request){
        Cart cart=carts.getOrCreate(account);if(cart.getItems().isEmpty())throw new BusinessException("購物車目前沒有商品");String payment=normalize(request.paymentMethod(),PAYMENT_METHODS,"付款方式不正確");
        BigDecimal subtotal=BigDecimal.ZERO;for(CartItem cartItem:cart.getItems()){Product p=cartItem.getProduct();if(!("ACTIVE".equalsIgnoreCase(p.getStatus())||"AVAILABLE".equalsIgnoreCase(p.getStatus())))throw new BusinessException(p.getProductName()+" 目前無法購買");if(cartItem.getQuantity()>p.getAvailableStock())throw new BusinessException(p.getProductName()+" 庫存不足");subtotal=subtotal.add(p.getPrice().multiply(BigDecimal.valueOf(cartItem.getQuantity())));}
        BigDecimal shipping=subtotal.compareTo(new BigDecimal("10000"))>=0?BigDecimal.ZERO:new BigDecimal("60");Order order=new Order();CartItem first=cart.getItems().get(0);order.setOrderNumber(nextNumber());order.setMember(cart.getMember());order.setProduct(first.getProduct());order.setQuantity(first.getQuantity());order.setUnitPrice(first.getProduct().getPrice());order.setRecipientName(request.recipientName().trim());order.setRecipientPhone(request.recipientPhone().trim());order.setShippingAddress(request.recipientAddress().trim());order.setSubtotal(subtotal);order.setShippingFee(shipping);order.setTotalAmount(subtotal.add(shipping));order.setOrderStatus(OrderStatus.PENDING.name());order.setPaymentStatus("DEMO_CARD".equals(payment)?PaymentStatus.PAID.name():PaymentStatus.UNPAID.name());order.setShippingStatus(ShippingStatus.NOT_SHIPPED.name());order.setPaymentMethod(payment);order.setNote(request.note());
        for(CartItem cartItem:cart.getItems()){Product p=cartItem.getProduct();p.setStock(p.getStock()-cartItem.getQuantity());products.save(p);OrderItem item=new OrderItem();item.setOrder(order);item.setProductId(p.getId());item.setProductCode(p.getProductCode());item.setProductName(p.getProductName());item.setUnitPrice(p.getPrice());item.setQuantity(cartItem.getQuantity());item.setSubtotal(p.getPrice().multiply(BigDecimal.valueOf(cartItem.getQuantity())));order.getItems().add(item);}
        Order saved=orders.save(order);carts.clear(account);return map(saved);
    }
    @Transactional(readOnly=true) public List<OrderDetailResponse> memberOrders(String account){Long memberId=carts.findMember(account).getId();return orders.findByMember_IdOrderByCreatedAtDesc(memberId).stream().map(this::map).toList();}
    @Transactional(readOnly=true) public OrderDetailResponse memberOrder(String account,Long id){Long memberId=carts.findMember(account).getId();return map(orders.findByIdAndMemberId(id,memberId).orElseThrow(()->new ResourceNotFoundException("找不到指定訂單")));}
    @Transactional public OrderDetailResponse cancel(String account,Long id){Long memberId=carts.findMember(account).getId();Order order=orders.findByIdAndMemberId(id,memberId).orElseThrow(()->new ResourceNotFoundException("找不到指定訂單"));if(!Set.of("PENDING","CONFIRMED").contains(order.getOrderStatus()))throw new BusinessException("目前訂單狀態不可取消");restore(order);order.setOrderStatus(OrderStatus.CANCELLED.name());if(PaymentStatus.PAID.name().equals(order.getPaymentStatus()))order.setPaymentStatus(PaymentStatus.REFUNDED.name());order.setShippingStatus(ShippingStatus.NOT_SHIPPED.name());return map(orders.save(order));}
    @Transactional(readOnly=true) public PagedResponse<OrderDetailResponse> adminOrders(int page,int size){return PagedResponse.from(orders.findAll(PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by(Sort.Direction.DESC,"createdAt"))).map(this::map));}
    @Transactional(readOnly=true) public OrderDetailResponse adminOrder(Long id){return map(find(id));}
    @Transactional public OrderDetailResponse updateOrderStatus(Long id,String status){Order order=find(id);String value=normalize(status,EnumSet.allOf(OrderStatus.class).stream().map(Enum::name).collect(java.util.stream.Collectors.toSet()),"訂單狀態不正確");if(OrderStatus.CANCELLED.name().equals(order.getOrderStatus())&&!OrderStatus.CANCELLED.name().equals(value))throw new BusinessException("已取消的訂單不可恢復為其他狀態");if(OrderStatus.CANCELLED.name().equals(value)&&!OrderStatus.CANCELLED.name().equals(order.getOrderStatus()))restore(order);order.setOrderStatus(value);return map(orders.save(order));}
    @Transactional public OrderDetailResponse updatePaymentStatus(Long id,String status){Order order=find(id);order.setPaymentStatus(normalize(status,EnumSet.allOf(PaymentStatus.class).stream().map(Enum::name).collect(java.util.stream.Collectors.toSet()),"付款狀態不正確"));return map(orders.save(order));}
    @Transactional public OrderDetailResponse updateShippingStatus(Long id,String status){Order order=find(id);order.setShippingStatus(normalize(status,EnumSet.allOf(ShippingStatus.class).stream().map(Enum::name).collect(java.util.stream.Collectors.toSet()),"配送狀態不正確"));return map(orders.save(order));}
    private void restore(Order order){List<OrderItem> list=items(order);for(OrderItem item:list){products.findById(item.getProductId()).ifPresent(p->{p.setStock((p.getStock()==null?0:p.getStock())+item.getQuantity());products.save(p);});}}
    private Order find(Long id){return orders.findById(id).orElseThrow(()->new ResourceNotFoundException("找不到指定訂單"));}
    private List<OrderItem> items(Order order){if(!order.getItems().isEmpty())return order.getItems();if(order.getProduct()==null)return List.of();OrderItem legacy=new OrderItem();legacy.setProductId(order.getProduct().getId());legacy.setProductCode(order.getProduct().getProductCode());legacy.setProductName(order.getProduct().getProductName());legacy.setUnitPrice(order.getUnitPrice());legacy.setQuantity(order.getQuantity());legacy.setSubtotal(order.getUnitPrice().multiply(BigDecimal.valueOf(order.getQuantity())));return List.of(legacy);}
    private OrderDetailResponse map(Order o){List<OrderItemDetailResponse> details=items(o).stream().map(i->new OrderItemDetailResponse(i.getId(),i.getProductId(),i.getProductCode(),i.getProductName(),i.getUnitPrice(),i.getQuantity(),i.getSubtotal())).toList();BigDecimal subtotal=o.getSubtotal()==null?details.stream().map(OrderItemDetailResponse::subtotal).reduce(BigDecimal.ZERO,BigDecimal::add):o.getSubtotal();return new OrderDetailResponse(o.getId(),o.getOrderNumber()==null?"LEGACY-"+o.getId():o.getOrderNumber(),o.getMember().getId(),o.getMember().getName(),o.getRecipientName(),o.getRecipientPhone(),o.getShippingAddress(),subtotal,o.getShippingFee()==null?BigDecimal.ZERO:o.getShippingFee(),o.getTotalAmount(),o.getOrderStatus(),o.getPaymentStatus()==null?PaymentStatus.UNPAID.name():o.getPaymentStatus(),o.getShippingStatus()==null?ShippingStatus.NOT_SHIPPED.name():o.getShippingStatus(),o.getPaymentMethod()==null?"LEGACY":o.getPaymentMethod(),o.getNote(),details,o.getCreatedAt(),o.getUpdatedAt());}
    private String nextNumber(){String base="SP"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));String value=base+String.format("%04d",new Random().nextInt(10000));while(orders.existsByOrderNumber(value))value=base+String.format("%04d",new Random().nextInt(10000));return value;}
    private String normalize(String value,Set<String> allowed,String message){String normalized=value==null?"":value.trim().toUpperCase();if(!allowed.contains(normalized))throw new BusinessException(message);return normalized;}
}
