package com.example.secondphone.service;
import java.time.LocalDateTime;import java.time.format.DateTimeFormatter;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.example.secondphone.dto.*;import com.example.secondphone.entity.*;import com.example.secondphone.exception.*;import com.example.secondphone.repository.*;
@Service @Transactional(readOnly=true)
public class TradeInService{
 private final TradeInRepository tradeIns;private final MemberRepository members;public TradeInService(TradeInRepository tradeIns,MemberRepository members){this.tradeIns=tradeIns;this.members=members;}
 @Transactional public TradeInResponse submit(String account,TradeInRequest q){Member member=member(account);TradeIn t=new TradeIn();t.setTradeInNumber(nextNumber());t.setMember(member);applyPublic(t,q);t.setStatus(TradeInStatus.SUBMITTED.name());return map(tradeIns.save(t));}
 public List<TradeInResponse> memberList(String account){Long memberId=member(account).getId();return tradeIns.findByMemberIdOrderByCreatedAtDesc(memberId).stream().map(this::map).toList();}
 public TradeInResponse memberDetail(String account,Long id){return map(owned(account,id));}
 @Transactional public TradeInResponse respond(String account,Long id,boolean accept){TradeIn t=owned(account,id);if(!TradeInStatus.QUOTED.name().equals(t.getStatus()))throw new BusinessException("目前狀態無法回覆報價");t.setStatus(accept?TradeInStatus.ACCEPTED.name():TradeInStatus.REJECTED.name());if(!accept)t.setRejectionReason("會員婉拒報價");return map(tradeIns.save(t));}
 public List<TradeInResponse> adminList(){return tradeIns.findAllByOrderByCreatedAtDesc().stream().map(this::map).toList();}public TradeInResponse adminDetail(Long id){return map(find(id));}
 @Transactional public TradeInResponse adminUpdate(Long id,TradeInAdminUpdateRequest q){TradeIn t=find(id);String status=normalize(q.status());if(TradeInStatus.QUOTED.name().equals(status)&&(q.quotedPrice()==null))throw new BusinessException("提出報價時必須填寫報價金額");if(TradeInStatus.REJECTED.name().equals(status)&&(q.rejectionReason()==null||q.rejectionReason().isBlank()))throw new BusinessException("拒絕收購時必須填寫原因");t.setStatus(status);t.setQuotedPrice(q.quotedPrice());t.setRejectionReason(q.rejectionReason());return map(tradeIns.save(t));}
 private void applyPublic(TradeIn t,TradeInRequest q){t.setCustomerName(q.customerName().trim());t.setCustomerPhone(q.customerPhone().trim());t.setBrand(q.brand().trim());t.setModel(q.model().trim());t.setStorageCapacity(q.storageCapacity());t.setColor(q.color());t.setImei(q.imei());t.setAppearanceCondition(q.appearanceCondition().trim());t.setFunctionCondition(q.functionCondition().trim());t.setDescription(q.description());t.setExpectedPrice(q.expectedPrice());}
 private Member member(String account){return members.findByAccountIgnoreCaseOrEmailIgnoreCase(account,account).orElseThrow(()->new ResourceNotFoundException("找不到登入會員"));}private TradeIn owned(String account,Long id){return tradeIns.findByIdAndMemberId(id,member(account).getId()).orElseThrow(()->new ResourceNotFoundException("找不到收購申請"));}private TradeIn find(Long id){return tradeIns.findById(id).orElseThrow(()->new ResourceNotFoundException("找不到收購申請"));}
 private String normalize(String value){try{return TradeInStatus.valueOf(value.trim().toUpperCase()).name();}catch(Exception e){throw new BusinessException("收購狀態不正確");}}private String nextNumber(){String base="TI"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));String value=base+String.format("%03d",new Random().nextInt(1000));while(tradeIns.existsByTradeInNumber(value))value=base+String.format("%03d",new Random().nextInt(1000));return value;}
 private TradeInResponse map(TradeIn t){return new TradeInResponse(t.getId(),t.getTradeInNumber(),t.getMember().getId(),t.getMember().getName(),t.getCustomerName(),t.getCustomerPhone(),t.getBrand(),t.getModel(),t.getStorageCapacity(),t.getColor(),t.getImei(),t.getAppearanceCondition(),t.getFunctionCondition(),t.getDescription(),t.getExpectedPrice(),t.getQuotedPrice(),t.getStatus(),t.getRejectionReason(),t.getCreatedAt(),t.getUpdatedAt());}
}
