<script setup>
import { ref,watch } from 'vue'
import { useAuthStore } from '../stores/auth'
import { useCartStore } from '../stores/cart'
const auth=useAuthStore(),cart=useCartStore(),menuOpen=ref(false)
watch(()=>auth.isAuthenticated,async loggedIn=>{if(loggedIn){try{await cart.load()}catch{}}else cart.reset()},{immediate:true})
const closeMenu=()=>{menuOpen.value=false}
</script>
<template><div class="app-shell"><header class="public-header"><div class="header-inner"><RouterLink class="brand" to="/" @click="closeMenu"><span class="brand-mark">S</span><span>Second Phone<small>安心二手機平台</small></span></RouterLink><button class="menu-toggle" type="button" :aria-expanded="menuOpen" aria-label="切換主選單" @click="menuOpen=!menuOpen">☰</button><nav :class="['public-nav',{open:menuOpen}]" aria-label="主要導覽"><RouterLink to="/" @click="closeMenu">首頁</RouterLink><RouterLink to="/products" @click="closeMenu">二手手機</RouterLink><RouterLink to="/repairs" @click="closeMenu">維修服務</RouterLink><RouterLink to="/trade-in" @click="closeMenu">舊機收購</RouterLink><RouterLink to="/about" @click="closeMenu">關於平台</RouterLink></nav><div class="header-actions"><RouterLink class="cart-link" to="/cart">購物車 <span class="cart-count">{{cart.itemCount}}</span></RouterLink><RouterLink v-if="auth.isStaff" class="button button-ghost button-small" to="/admin">{{auth.currentUser?.name}}・後台</RouterLink><RouterLink v-else-if="auth.isAuthenticated" class="button button-ghost button-small" to="/member">{{auth.currentUser?.name}}・會員中心</RouterLink><RouterLink v-else class="button button-primary button-small" to="/login">登入</RouterLink></div></div></header><main class="public-main"><RouterView/></main><footer class="site-footer"><div class="footer-grid container-wide"><div><strong>Second Phone</strong><p>透明檢測、安心交易、完整售後，讓每一支手機延續價值。</p></div><div><h3>平台服務</h3><RouterLink to="/products">選購二手機</RouterLink><RouterLink to="/repairs">手機維修</RouterLink><RouterLink to="/trade-in">舊機收購</RouterLink></div><div><h3>服務承諾</h3><span>透明機況分級</span><span>售後品質保障</span><span>個資安全保護</span></div></div><div class="footer-bottom">© 2026 Second Phone Platform．期末企業型展示版本</div></footer></div></template>
