<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { getAdminOrder, updateAdminOrderStatus, updateAdminPaymentStatus, updateAdminShippingStatus } from '../api/orderApi'
const route=useRoute(),order=ref(null),loading=ref(true),busy=ref(''),error=ref(''),success=ref(''),form=reactive({orderStatus:'',paymentStatus:'',shippingStatus:''})
const money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(v||0)
function sync(value){order.value=value;form.orderStatus=value.orderStatus;form.paymentStatus=value.paymentStatus;form.shippingStatus=value.shippingStatus}
async function load(){try{sync(await getAdminOrder(route.params.id))}catch(e){error.value=e.message}finally{loading.value=false}}
async function update(type){busy.value=type;error.value='';success.value='';try{const api=type==='order'?updateAdminOrderStatus:type==='payment'?updateAdminPaymentStatus:updateAdminShippingStatus;sync(await api(order.value.id,form[`${type}Status`]));success.value='訂單狀態已更新。'}catch(e){error.value=e.message}finally{busy.value=''}}
onMounted(load)
</script>
<template><section class="admin-page"><RouterLink class="back-link" to="/admin/orders">← 返回訂單管理</RouterLink><p v-if="error" class="alert alert-error">{{ error }}</p><p v-if="success" class="alert alert-success">{{ success }}</p><div v-if="loading" class="loading-state">正在載入訂單…</div><template v-else-if="order"><div class="page-heading"><div><span class="eyebrow">ORDER CONTROL</span><h1>{{ order.orderNumber }}</h1><p>{{ order.memberName }} · {{ new Date(order.createdAt).toLocaleString('zh-TW') }}</p></div></div><section class="card status-editor"><label>訂單狀態<select v-model="form.orderStatus"><option v-for="value in ['PENDING','CONFIRMED','PROCESSING','COMPLETED','CANCELLED']" :key="value">{{ value }}</option></select></label><button class="button button-secondary" :disabled="busy" @click="update('order')">更新</button><label>付款狀態<select v-model="form.paymentStatus"><option v-for="value in ['UNPAID','PAID','REFUNDED']" :key="value">{{ value }}</option></select></label><button class="button button-secondary" :disabled="busy" @click="update('payment')">更新</button><label>配送狀態<select v-model="form.shippingStatus"><option v-for="value in ['NOT_SHIPPED','PREPARING','SHIPPED','DELIVERED']" :key="value">{{ value }}</option></select></label><button class="button button-secondary" :disabled="busy" @click="update('shipping')">更新</button></section><div class="order-detail-grid"><section class="card"><h2>商品明細</h2><div v-for="item in order.items" :key="item.id || item.productId" class="order-line"><div><strong>{{ item.productName }}</strong><p>{{ item.productCode }} · {{ money(item.unitPrice) }} × {{ item.quantity }}</p></div><strong>{{ money(item.subtotal) }}</strong></div></section><aside class="card order-summary"><h2>收件與金額</h2><p><strong>{{ order.recipientName }}</strong><br>{{ order.recipientPhone }}<br>{{ order.recipientAddress }}</p><div class="summary-line"><span>商品小計</span><strong>{{ money(order.subtotal) }}</strong></div><div class="summary-line"><span>運費</span><strong>{{ money(order.shippingFee) }}</strong></div><div class="summary-line total"><span>訂單總額</span><strong>{{ money(order.totalAmount) }}</strong></div></aside></div></template></section></template>
