<script setup>
import { onMounted, reactive, ref } from 'vue'
import { adjustInventory, getInventoryMovements, getProducts } from '../api/productApi'
const products=ref([]),movements=ref([]),loading=ref(false),saving=ref(false),error=ref(''),success=ref(''),page=ref(0),totalPages=ref(0),form=reactive({productId:'',type:'IN',quantity:1,reason:''})
async function load(){loading.value=true;try{const [productPage,movementPage]=await Promise.all([getProducts({size:60,sort:'productName',direction:'asc'}),getInventoryMovements({page:page.value,size:20})]);products.value=productPage.content||[];movements.value=movementPage.content||[];totalPages.value=movementPage.totalPages||0}catch(e){error.value=e.message}finally{loading.value=false}}
async function submit(){saving.value=true;error.value='';success.value='';try{await adjustInventory(form.productId,{type:form.type,quantity:Number(form.quantity),reason:form.reason});success.value='庫存已完成異動並留下紀錄。';form.quantity=1;form.reason='';await load()}catch(e){error.value=e.message}finally{saving.value=false}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">INVENTORY CONTROL</p><h1>庫存管理</h1><p>所有增加、減少與調整都會保存操作前後數量。</p></div></div><p v-if="error" class="alert error">{{error}}</p><p v-if="success" class="alert success">{{success}}</p><form class="card inventory-form" @submit.prevent="submit"><div><h2>建立庫存異動</h2><p>減少庫存時系統會阻止負庫存與低於保留量。</p></div><label>商品 *<select v-model="form.productId" required><option value="">請選擇商品</option><option v-for="p in products" :key="p.id" :value="p.id">{{p.productCode}}・{{p.productName}}（現有 {{p.stock}}）</option></select></label><label>異動類型<select v-model="form.type"><option value="IN">入庫</option><option value="OUT">出庫</option><option value="ADJUSTMENT">差額調整</option></select></label><label>數量 *<input v-model.number="form.quantity" type="number" :min="form.type==='ADJUSTMENT'?undefined:1" required></label><label>原因 *<input v-model.trim="form.reason" required maxlength="255" placeholder="例如：供應商到貨"></label><button class="button button-primary" :disabled="saving">{{saving?'處理中…':'確認異動'}}</button></form><div class="card"><div class="card-header"><div><h2>異動紀錄</h2><p>依時間由新至舊排列。</p></div></div><div v-if="loading" class="loading-row">載入庫存資料中…</div><div v-else-if="!movements.length" class="empty-inline">目前尚無庫存異動紀錄。</div><div v-else class="table-scroll"><table><thead><tr><th>時間</th><th>商品</th><th>類型</th><th>異動</th><th>異動前</th><th>異動後</th><th>原因</th><th>操作人員</th></tr></thead><tbody><tr v-for="m in movements" :key="m.id"><td>{{m.createdAt?.replace('T',' ').slice(0,16)}}</td><td><b>{{m.productName}}</b><small>{{m.productCode}}</small></td><td><span class="badge">{{{IN:'入庫',OUT:'出庫',ADJUSTMENT:'調整'}[m.type]}}</span></td><td :class="m.changeQuantity>0?'text-success':'text-danger'">{{m.changeQuantity>0?'+':''}}{{m.changeQuantity}}</td><td>{{m.beforeStock}}</td><td>{{m.afterStock}}</td><td>{{m.reason}}</td><td>{{m.operatorUsername}}</td></tr></tbody></table></div><nav v-if="totalPages>1" class="pagination"><button :disabled="page===0" @click="page--;load()">上一頁</button><span>第 {{page+1}}／{{totalPages}} 頁</span><button :disabled="page>=totalPages-1" @click="page++;load()">下一頁</button></nav></div></section></template>
