<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { cancelMyOrder, getMyOrder } from '../api/orderApi'
import ConfirmModal from '../components/ConfirmModal.vue'

const route=useRoute(),order=ref(null),loading=ref(true),error=ref(''),success=ref(''),confirmCancel=ref(false),busy=ref(false)
const money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(v||0)
const statusLabels={PENDING:'待確認',CONFIRMED:'已確認',PROCESSING:'處理中',COMPLETED:'已完成',CANCELLED:'已取消',UNPAID:'未付款',PAID:'已付款',REFUNDED:'已退款',NOT_SHIPPED:'未出貨',PREPARING:'備貨中',SHIPPED:'已出貨',DELIVERED:'已送達'}
async function load(){loading.value=true;try{order.value=await getMyOrder(route.params.id)}catch(e){error.value=e.message}finally{loading.value=false}}
async function cancel(){busy.value=true;error.value='';try{order.value=await cancelMyOrder(order.value.id);success.value='訂單已取消，庫存已恢復。';confirmCancel.value=false}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="member-section"><RouterLink class="back-link" to="/member/orders">← 返回我的訂單</RouterLink><p v-if="error" class="alert alert-error">{{ error }}</p><p v-if="success" class="alert alert-success">{{ success }}</p><div v-if="loading" class="loading-state">正在載入訂單…</div><template v-else-if="order"><div class="page-heading"><div><span class="eyebrow">ORDER DETAIL</span><h1>{{ order.orderNumber }}</h1><p>{{ new Date(order.createdAt).toLocaleString('zh-TW') }}</p></div><button v-if="['PENDING','CONFIRMED'].includes(order.orderStatus)" class="button button-danger" @click="confirmCancel=true">取消訂單</button></div><div class="status-grid"><div class="card"><span>訂單狀態</span><strong>{{ statusLabels[order.orderStatus] || order.orderStatus }}</strong></div><div class="card"><span>付款狀態</span><strong>{{ statusLabels[order.paymentStatus] || order.paymentStatus }}</strong></div><div class="card"><span>配送狀態</span><strong>{{ statusLabels[order.shippingStatus] || order.shippingStatus }}</strong></div></div><div class="order-detail-grid"><section class="card"><h2>商品明細</h2><div v-for="item in order.items" :key="item.id || item.productId" class="order-line"><div><strong>{{ item.productName }}</strong><p>{{ item.productCode }} · {{ money(item.unitPrice) }} × {{ item.quantity }}</p></div><strong>{{ money(item.subtotal) }}</strong></div></section><aside class="card order-summary"><h2>配送與金額</h2><p><strong>{{ order.recipientName }}</strong><br>{{ order.recipientPhone }}<br>{{ order.recipientAddress }}</p><div class="summary-line"><span>商品小計</span><strong>{{ money(order.subtotal) }}</strong></div><div class="summary-line"><span>運費</span><strong>{{ money(order.shippingFee) }}</strong></div><div class="summary-line total"><span>訂單總額</span><strong>{{ money(order.totalAmount) }}</strong></div><p class="muted">付款方式：{{ order.paymentMethod === 'DEMO_CARD' ? '展示用模擬信用卡' : '貨到付款（展示）' }}</p></aside></div></template><ConfirmModal :open="confirmCancel" title="取消訂單" message="確定要取消這筆訂單嗎？取消後會恢復商品庫存。" :busy="busy" @cancel="confirmCancel=false" @confirm="cancel" /></section></template>
