<script setup>
import { onMounted, ref } from 'vue'
import { getAdminOrders } from '../api/orderApi'
const page=ref(0),result=ref({content:[],totalPages:0,totalElements:0}),loading=ref(true),error=ref('')
const money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(v||0)
const labels={PENDING:'待確認',CONFIRMED:'已確認',PROCESSING:'處理中',COMPLETED:'已完成',CANCELLED:'已取消'}
async function load(next=page.value){loading.value=true;error.value='';try{result.value=await getAdminOrders({page:next,size:12});page.value=next}catch(e){error.value=e.message}finally{loading.value=false}}
onMounted(()=>load())
</script>
<template><section class="admin-page"><div class="page-heading"><div><span class="eyebrow">ORDER MANAGEMENT</span><h1>訂單管理</h1><p>共 {{ result.totalElements || 0 }} 筆訂單，可查看付款與配送狀態。</p></div></div><p v-if="error" class="alert alert-error">{{ error }}</p><div class="card table-card"><div v-if="loading" class="loading-state">正在載入訂單…</div><div v-else-if="!result.content?.length" class="empty-state"><h2>目前沒有訂單</h2></div><div v-else class="table-scroll"><table><thead><tr><th>訂單編號</th><th>會員</th><th>金額</th><th>訂單狀態</th><th>付款</th><th>配送</th><th>建立時間</th><th>操作</th></tr></thead><tbody><tr v-for="order in result.content" :key="order.id"><td><strong>{{ order.orderNumber }}</strong></td><td>{{ order.memberName }}</td><td>{{ money(order.totalAmount) }}</td><td><span class="badge">{{ labels[order.orderStatus] || order.orderStatus }}</span></td><td>{{ order.paymentStatus }}</td><td>{{ order.shippingStatus }}</td><td>{{ new Date(order.createdAt).toLocaleString('zh-TW') }}</td><td><RouterLink class="button button-secondary button-small" :to="`/admin/orders/${order.id}`">管理</RouterLink></td></tr></tbody></table></div><nav v-if="result.totalPages>1" class="pagination"><button :disabled="page===0" @click="load(page-1)">上一頁</button><span>第 {{ page+1 }}／{{ result.totalPages }} 頁</span><button :disabled="page>=result.totalPages-1" @click="load(page+1)">下一頁</button></nav></div></section></template>
