<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {getMembers} from '../api/memberApi';import {getProducts} from '../api/productApi';import {createOrder,deleteOrder,getOrders,updateOrder} from '../api/orderApi'
const orders=ref([]),members=ref([]),products=ref([]),loading=ref(false),saving=ref(false),errorMessage=ref(''),editingId=ref(null)
const filters=reactive({keyword:'',status:''});const blank=()=>({memberId:'',productId:'',quantity:1,orderStatus:'PENDING',recipientName:'',recipientPhone:'',shippingAddress:'',note:''});const form=reactive(blank())
const selectedProduct=computed(()=>products.value.find(p=>p.id===Number(form.productId)));const estimatedTotal=computed(()=>Number(selectedProduct.value?.price||0)*Number(form.quantity||0))
const money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD'}).format(Number(v)||0);const date=v=>v?new Date(v).toLocaleString('zh-TW'):'-';const labels={PENDING:'待確認',CONFIRMED:'已確認',SHIPPED:'已出貨',COMPLETED:'已完成',CANCELLED:'已取消'};const message=e=>e?.response?.data?.message||e?.message||'操作失敗，請稍後再試'
async function load(){loading.value=true;errorMessage.value='';try{orders.value=await getOrders(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)))}catch(e){errorMessage.value=message(e)}finally{loading.value=false}}
function edit(o){editingId.value=o.id;Object.assign(form,{memberId:o.memberId,productId:o.productId,quantity:o.quantity,orderStatus:o.orderStatus,recipientName:o.recipientName,recipientPhone:o.recipientPhone,shippingAddress:o.shippingAddress,note:o.note||''});scrollTo({top:0,behavior:'smooth'})}
function reset(){editingId.value=null;Object.assign(form,blank())}
async function submit(){saving.value=true;errorMessage.value='';try{const data={...form,memberId:Number(form.memberId),productId:Number(form.productId),quantity:Number(form.quantity)};editingId.value?await updateOrder(editingId.value,data):await createOrder(data);reset();await load()}catch(e){errorMessage.value=message(e)}finally{saving.value=false}}
async function remove(o){if(!confirm(`確定刪除訂單 #${o.id}？`))return;try{await deleteOrder(o.id);await load()}catch(e){errorMessage.value=message(e)}}function clear(){Object.assign(filters,{keyword:'',status:''});load()}
onMounted(async()=>{try{[members.value,products.value]=await Promise.all([getMembers(),getProducts()]);await load()}catch(e){errorMessage.value=message(e)}})
</script>
<template><section class="management-page"><div class="page-heading"><div><h2>訂單管理</h2><p>價格與正式總金額由後端計算，訂單異動會同步調整庫存。</p></div><button class="secondary" :disabled="loading" @click="load">{{loading?'載入中...':'重新整理'}}</button></div><p v-if="errorMessage" class="alert error">{{errorMessage}}</p>
<form class="card" @submit.prevent="submit"><h3>{{editingId?`編輯訂單 #${editingId}`:'新增訂單'}}</h3><div class="form-grid"><label>會員 *<select v-model="form.memberId" required><option value="" disabled>請選擇</option><option v-for="m in members" :key="m.id" :value="m.id">{{m.id}}－{{m.account}}－{{m.name}}</option></select></label><label>商品 *<select v-model="form.productId" required><option value="" disabled>請選擇</option><option v-for="p in products" :key="p.id" :value="p.id">{{p.productName}} / {{money(p.price)}} / 庫存 {{p.stock??0}}</option></select></label><label>數量 *<input v-model.number="form.quantity" type="number" min="1" required></label><label>狀態<select v-model="form.orderStatus"><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></label><label>收件人 *<input v-model.trim="form.recipientName" required></label><label>電話 *<input v-model.trim="form.recipientPhone" required></label><label class="full-width">地址 *<input v-model.trim="form.shippingAddress" required></label><label class="full-width">備註<textarea v-model.trim="form.note" rows="3"></textarea></label></div><p class="summary-box">預估總金額：{{money(estimatedTotal)}}（後端計算結果為準）</p><div class="form-actions"><button class="primary" :disabled="saving">{{saving?'處理中...':editingId?'儲存修改':'新增訂單'}}</button><button v-if="editingId" type="button" class="secondary" @click="reset">取消編輯</button></div></form>
<form class="card search-bar" @submit.prevent="load"><label>關鍵字<input v-model.trim="filters.keyword" placeholder="會員、商品或收件人"></label><label>狀態<select v-model="filters.status"><option value="">全部</option><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></label><button class="primary">搜尋</button><button type="button" class="secondary" @click="clear">清除</button></form>
<div class="card"><h3>訂單列表</h3><p v-if="loading">載入中...</p><p v-else-if="!orders.length">目前沒有訂單。</p><div v-else class="table-scroll"><table><thead><tr><th>ID</th><th>會員</th><th>商品</th><th>數量</th><th>單價</th><th>總金額</th><th>狀態</th><th>收件人</th><th>電話</th><th>建立時間</th><th>操作</th></tr></thead><tbody><tr v-for="o in orders" :key="o.id"><td>{{o.id}}</td><td>{{o.memberName}}</td><td>{{o.productName}}</td><td>{{o.quantity}}</td><td>{{money(o.unitPrice)}}</td><td>{{money(o.totalAmount)}}</td><td><span class="badge">{{labels[o.orderStatus]||o.orderStatus}}</span></td><td>{{o.recipientName}}</td><td>{{o.recipientPhone}}</td><td>{{date(o.createdAt)}}</td><td class="row-actions"><button class="secondary small" @click="edit(o)">編輯</button><button class="danger small" @click="remove(o)">刪除</button></td></tr></tbody></table></div></div></section></template>
