<script setup>
import { onMounted, reactive, ref } from 'vue'
import { addProductImage, createProduct, deleteProduct, deleteProductImage, getBrands, getCategories, getProducts, updateProduct, uploadProductImage } from '../api/productApi'
import { useAuthStore } from '../stores/auth'
import ConfirmModal from '../components/ConfirmModal.vue'
import ProductCsvImportModal from '../components/ProductCsvImportModal.vue'
import ProductImageBackfillPreviewModal from '../components/ProductImageBackfillPreviewModal.vue'
const auth = useAuthStore(), products = ref([]), brands = ref([]), categories = ref([]), loading = ref(false), saving = ref(false), error = ref(''), success = ref(''), editingId = ref(null), totalPages = ref(0), page = ref(0), deleteTarget = ref(null), imageUrl = ref('')
const filters = reactive({ keyword: '', status: '' })
const uploadFile = ref(null)
const csvDialogOpen = ref(false)
const imageBackfillOpen = ref(false)
const empty = () => ({ productCode: '', productName: '', brandId: '', brand: '', categoryId: '', model: '', storageCapacity: '', color: '', conditionLevel: 'GOOD', cost: 0, price: 0, stock: 0, reservedStock: 0, description: '', imageUrl: '', status: 'ACTIVE', featured: false, images: [] })
const form = reactive(empty())
const statuses = { DRAFT: '草稿', ACTIVE: '上架', OUT_OF_STOCK: '缺貨', DISCONTINUED: '停售', AVAILABLE: '上架' }
async function load() { loading.value=true; error.value=''; try { const data=await getProducts({ keyword: filters.keyword || undefined, status: filters.status || undefined, page: page.value, size: 10 }); products.value=data.content || []; totalPages.value=data.totalPages || 0 } catch(e){ error.value=e.message } finally{ loading.value=false } }
function reset() { editingId.value=null; Object.assign(form, empty()); imageUrl.value='' }
function edit(item) { editingId.value=item.id; Object.assign(form, { ...empty(), ...item, brandId:item.brandId || '', categoryId:item.categoryId || '', images:item.images || [] }); window.scrollTo({ top:0, behavior:'smooth' }) }
async function submit() { saving.value=true; error.value=''; success.value=''; try { const payload={ ...form, brandId:form.brandId || null, categoryId:form.categoryId || null, cost:Number(form.cost), price:Number(form.price), stock:Number(form.stock), reservedStock:Number(form.reservedStock), images:undefined }; if(editingId.value) await updateProduct(editingId.value,payload); else await createProduct(payload); success.value=editingId.value?'商品已更新。':'商品已新增。'; reset(); await load() } catch(e){ error.value=e.message } finally{ saving.value=false } }
async function addImage() { if(!editingId.value || !imageUrl.value) return; try { await addProductImage(editingId.value,{ imageUrl:imageUrl.value, altText:form.productName, primaryImage:form.images.length===0, sortOrder:form.images.length }); success.value='商品圖片已新增。'; const refreshed=(await getProducts({keyword:form.productCode,size:1})).content?.[0]; if(refreshed) edit(refreshed); imageUrl.value=''; await load() } catch(e){ error.value=e.message } }
async function removeImage(image) { try { await deleteProductImage(editingId.value,image.id); success.value='商品圖片已移除。'; form.images=form.images.filter(i=>i.id!==image.id); await load() } catch(e){ error.value=e.message } }
async function uploadImage() { if(!editingId.value || !uploadFile.value) return; saving.value=true; error.value=''; try { await uploadProductImage(editingId.value,uploadFile.value,form.images.length===0,form.images.length); success.value='商品圖片已上傳。'; uploadFile.value=null; const refreshed=(await getProducts({keyword:form.productCode,size:1})).content?.[0]; if(refreshed) edit(refreshed); await load() } catch(e){ error.value=e.message } finally{saving.value=false} }
async function confirmDelete() { saving.value=true; try { await deleteProduct(deleteTarget.value.id); deleteTarget.value=null; success.value='商品已刪除。'; await load() } catch(e){ error.value=e.message } finally{ saving.value=false } }
async function csvImported(result) { success.value=`CSV 匯入完成：成功 ${result.successCount} 筆、略過 ${result.skippedCount} 筆、失敗 ${result.failedCount} 筆。`; await load() }
async function imageBackfillApplied(result) { success.value=`商品圖片補齊完成：更新 ${result.updatedProducts} 筆、略過 ${result.skippedProducts} 筆、失敗機型 ${result.failedModels} 個。`; await load() }
const money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(v||0)
onMounted(async()=>{ try { [brands.value,categories.value]=await Promise.all([getBrands(true),getCategories(true)]) } catch(e){ error.value=e.message } await load() })
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">PRODUCT OPERATIONS</p><h1>商品管理</h1><p>管理商品規格、上下架、價格、主圖與可售庫存。</p></div><div class="row-actions"><button class="button button-primary" @click="csvDialogOpen=true">CSV 批次匯入</button><button class="button button-secondary" @click="imageBackfillOpen=true">自動補齊商品圖片</button><button class="button button-ghost" @click="load">重新整理</button></div></div><p v-if="error" class="alert error">{{ error }}</p><p v-if="success" class="alert success">{{ success }}</p><ProductCsvImportModal v-if="csvDialogOpen" :brands="brands" :categories="categories" @close="csvDialogOpen=false" @imported="csvImported" @error="error=$event.message" /><ProductImageBackfillPreviewModal v-if="imageBackfillOpen" @close="imageBackfillOpen=false" @applied="imageBackfillApplied" />
<form class="card form-card" @submit.prevent="submit"><div class="card-header"><div><h2>{{ editingId ? `編輯商品 #${editingId}` : '新增商品' }}</h2><p>星號欄位為必填。</p></div><button v-if="editingId" type="button" class="button button-ghost button-small" @click="reset">取消編輯</button></div><div class="form-grid"><label>商品編號<input v-model.trim="form.productCode" maxlength="40" placeholder="留空由系統產生"></label><label>商品名稱 *<input v-model.trim="form.productName" required maxlength="150"></label><label>品牌 *<select v-model="form.brandId"><option value="">使用既有文字品牌</option><option v-for="b in brands" :key="b.id" :value="b.id">{{ b.name }}</option></select></label><label v-if="!form.brandId">品牌名稱 *<input v-model.trim="form.brand" required maxlength="50"></label><label>分類<select v-model="form.categoryId"><option value="">未分類</option><option v-for="c in categories" :key="c.id" :value="c.id">{{ c.name }}</option></select></label><label>型號 *<input v-model.trim="form.model" required maxlength="100"></label><label>容量<input v-model.trim="form.storageCapacity" maxlength="30" placeholder="128GB"></label><label>顏色<input v-model.trim="form.color" maxlength="50"></label><label>機況 *<select v-model="form.conditionLevel"><option value="NEW">全新</option><option value="LIKE_NEW">近全新</option><option value="EXCELLENT">優良</option><option value="GOOD">良好</option><option value="FAIR">可用</option></select></label><label>成本<input v-model.number="form.cost" type="number" min="0" step="1"></label><label>售價 *<input v-model.number="form.price" type="number" min="0" step="1" required></label><label>總庫存 *<input v-model.number="form.stock" type="number" min="0" required></label><label>保留庫存<input v-model.number="form.reservedStock" type="number" min="0"></label><label>狀態 *<select v-model="form.status"><option value="DRAFT">草稿</option><option value="ACTIVE">上架</option><option value="OUT_OF_STOCK">缺貨</option><option value="DISCONTINUED">停售</option></select></label><label class="check-label"><input v-model="form.featured" type="checkbox"> 首頁精選商品</label><label class="full-width">主圖網址<input v-model.trim="form.imageUrl" type="url" maxlength="500"></label><label class="full-width">商品說明<textarea v-model.trim="form.description" rows="4"></textarea></label></div><div class="form-actions"><button class="button button-primary" :disabled="saving">{{ saving ? '儲存中…' : editingId ? '儲存修改' : '新增商品' }}</button></div>
<div v-if="editingId" class="image-manager"><h3>多張商品圖片</h3><p class="muted">可上傳 JPG、PNG、WebP（上限 5MB），或新增 HTTPS 圖片網址。</p><div class="inline-form image-upload-row"><input type="file" accept="image/jpeg,image/png,image/webp" @change="uploadFile=$event.target.files[0] || null"><button type="button" class="button button-primary" :disabled="!uploadFile || saving" @click="uploadImage">上傳圖片</button></div><div class="inline-form"><input v-model.trim="imageUrl" type="url" placeholder="貼上 HTTPS 圖片網址"><button type="button" class="button button-secondary" @click="addImage">新增網址</button></div><div v-if="form.images.length" class="image-list"><div v-for="image in form.images" :key="image.id"><img :src="image.imageUrl" :alt="image.altText"><span v-if="image.primaryImage" class="badge badge-success">主圖</span><button type="button" @click="removeImage(image)">移除</button></div></div><p v-else class="muted">尚無額外圖片。第一張新增圖片會自動設為主圖。</p></div></form>
<div class="card"><div class="card-header"><div><h2>商品清單</h2><p>顯示商品編號、售價、庫存與狀態。</p></div><form class="table-filters" @submit.prevent="page=0;load()"><input v-model.trim="filters.keyword" placeholder="搜尋商品"><select v-model="filters.status"><option value="">全部狀態</option><option value="ACTIVE">上架</option><option value="DRAFT">草稿</option><option value="OUT_OF_STOCK">缺貨</option><option value="DISCONTINUED">停售</option></select><button class="button button-primary button-small">搜尋</button></form></div><div v-if="loading" class="loading-row">載入商品資料中…</div><div v-else-if="!products.length" class="empty-inline">尚無符合條件的商品。</div><div v-else class="table-scroll"><table><thead><tr><th>商品編號</th><th>主圖</th><th>名稱</th><th>品牌／分類</th><th>售價</th><th>庫存</th><th>可售</th><th>狀態</th><th>建立時間</th><th>操作</th></tr></thead><tbody><tr v-for="item in products" :key="item.id"><td><code>{{ item.productCode || '-' }}</code></td><td><img v-if="item.imageUrl" class="product-thumb" :src="item.imageUrl" :alt="item.productName"><span v-else class="image-placeholder">S</span></td><td><b>{{ item.productName }}</b><small>{{ item.model }}</small></td><td>{{ item.brand }}<small>{{ item.category || '未分類' }}</small></td><td>{{ money(item.price) }}</td><td>{{ item.stock }}</td><td :class="item.availableStock<=2?'text-danger':''">{{ item.availableStock }}</td><td><span :class="['badge', item.status==='ACTIVE'?'badge-success':item.status==='OUT_OF_STOCK'?'badge-danger':'']">{{ statuses[item.status] || item.status }}</span></td><td>{{ item.createdAt?.slice(0,10) || '-' }}</td><td><div class="row-actions"><button class="button button-ghost button-small" @click="edit(item)">編輯</button><button v-if="auth.isAdmin" class="button button-danger button-small" @click="deleteTarget=item">刪除</button></div></td></tr></tbody></table></div><nav v-if="totalPages>1" class="pagination"><button :disabled="page===0" @click="page--;load()">上一頁</button><span>第 {{ page+1 }}／{{ totalPages }} 頁</span><button :disabled="page>=totalPages-1" @click="page++;load()">下一頁</button></nav></div><ConfirmModal :open="!!deleteTarget" title="刪除商品" :message="`確定要刪除「${deleteTarget?.productName || ''}」嗎？此動作無法復原。`" :busy="saving" @cancel="deleteTarget=null" @confirm="confirmDelete" /></section></template>
