<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getBrands, getCategories, getProducts } from '../api/productApi'
import ProductCard from '../components/ProductCard.vue'
const route = useRoute(), router = useRouter(), products = ref([]), brands = ref([]), categories = ref([]), loading = ref(false), error = ref(''), totalPages = ref(0), totalElements = ref(0), filterOpen = ref(false)
const filters = reactive({ keyword: route.query.keyword || '', brandId: '', categoryId: '', condition: '', minPrice: '', maxPrice: '', inStock: false, sortValue: 'createdAt,desc', page: 0 })
async function load() { loading.value = true; error.value = ''; try { const [sort, direction] = filters.sortValue.split(','); const data = await getProducts({ keyword: filters.keyword || undefined, brandId: filters.brandId || undefined, categoryId: filters.categoryId || undefined, condition: filters.condition || undefined, minPrice: filters.minPrice || undefined, maxPrice: filters.maxPrice || undefined, inStock: filters.inStock || undefined, status: 'ACTIVE', page: filters.page, size: 12, sort, direction }); products.value = data.content || []; totalPages.value = data.totalPages || 0; totalElements.value = data.totalElements || 0; router.replace({ query: filters.keyword ? { keyword: filters.keyword } : {} }) } catch (e) { error.value = e.message } finally { loading.value = false } }
function applyFilters() { filters.page = 0; filterOpen.value = false; load() }
function clearFilters() { Object.assign(filters, { keyword: '', brandId: '', categoryId: '', condition: '', minPrice: '', maxPrice: '', inStock: false, sortValue: 'createdAt,desc', page: 0 }); load() }
function go(page) { filters.page = page; load() }
watch(() => filters.sortValue, applyFilters)
onMounted(async () => { try { [brands.value, categories.value] = await Promise.all([getBrands(), getCategories()]) } catch {} await load() })
</script>
<template><div class="catalog-page container-wide"><div class="page-hero"><p class="eyebrow">CERTIFIED DEVICES</p><h1>二手手機</h1><p>依預算與需求快速篩選，所有庫存資訊即時呈現。</p></div><div class="catalog-toolbar"><form class="catalog-search" @submit.prevent="applyFilters"><input v-model.trim="filters.keyword" placeholder="搜尋品牌、型號或商品名稱"><button class="button button-primary">搜尋</button></form><button class="button button-ghost mobile-filter-button" @click="filterOpen=true">篩選條件</button><select v-model="filters.sortValue" aria-label="商品排序"><option value="createdAt,desc">最新上架</option><option value="price,asc">價格低至高</option><option value="price,desc">價格高至低</option><option value="productName,asc">名稱排序</option></select></div><div class="catalog-layout"><aside :class="['filter-panel', { open: filterOpen }]"><div class="filter-header"><h2>篩選條件</h2><button @click="filterOpen=false">×</button></div><label>品牌<select v-model="filters.brandId"><option value="">全部品牌</option><option v-for="item in brands" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label>分類<select v-model="filters.categoryId"><option value="">全部分類</option><option v-for="item in categories" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label>機況<select v-model="filters.condition"><option value="">全部機況</option><option value="NEW">全新</option><option value="LIKE_NEW">近全新</option><option value="EXCELLENT">優良</option><option value="GOOD">良好</option><option value="FAIR">可用</option></select></label><div class="price-range"><label>最低價格<input v-model.number="filters.minPrice" type="number" min="0"></label><label>最高價格<input v-model.number="filters.maxPrice" type="number" min="0"></label></div><label class="check-label"><input v-model="filters.inStock" type="checkbox"> 僅顯示有庫存</label><button class="button button-primary button-full" @click="applyFilters">套用篩選</button><button class="button button-ghost button-full" @click="clearFilters">清除條件</button></aside><section class="catalog-results"><div class="result-summary"><span>共 {{ totalElements }} 項商品</span></div><p v-if="error" class="alert error">{{ error }}</p><div v-if="loading" class="product-grid"><div v-for="n in 6" :key="n" class="skeleton product-skeleton"></div></div><div v-else-if="products.length" class="product-grid"><ProductCard v-for="product in products" :key="product.id" :product="product" /></div><div v-else class="empty-state card"><span class="empty-icon">⌕</span><h2>找不到符合條件的商品</h2><p>試著調整品牌、機況或價格範圍。</p><button class="button button-primary" @click="clearFilters">清除篩選</button></div><nav v-if="totalPages > 1" class="pagination" aria-label="商品分頁"><button :disabled="filters.page===0" @click="go(filters.page-1)">上一頁</button><button v-for="page in totalPages" :key="page" :class="{ active: filters.page===page-1 }" @click="go(page-1)">{{ page }}</button><button :disabled="filters.page>=totalPages-1" @click="go(filters.page+1)">下一頁</button></nav></section></div></div></template>
